version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker_config/backend/Dockerfile
    env_file:
      - ./docker_config/backend/backend.env
    entrypoint: /external_pentest/docker_config/backend/server-entrypoint.sh
    expose:
      - 8000
    restart: on-failure
    volumes:
      - ./external_pentest/media:/var/www/media
      - ./external_pentest/aquatone_scans:/var/www/aquatone_scans
    depends_on:
      - rabbitmq
      - redis
      - db
    links:
      - db

  nginx:
    restart: always
    image: nginx:1.17
    ports:
      - "8080:8080"
    volumes:
      - ./docker_config/nginx/:/etc/nginx/conf.d
      - ./external_pentest/static:/external_pentest/external_pentest/static
      - ./external_pentest/media:/var/www/media
      - ./external_pentest/aquatone_scans:/var/www/aquatone_scans
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery_worker:
    build:
      context: .
      dockerfile: ./docker_config/backend/Dockerfile
    env_file:
      - ./docker_config/backend/backend.env
    entrypoint: /external_pentest/docker_config/backend/worker-entrypoint.sh
    volumes:
      - ./external_pentest/media:/var/www/media
      - ./external_pentest/aquatone_scans:/var/www/aquatone_scans
    depends_on:
      - web
      - redis

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  subfinder:
    build:
      context: .
      dockerfile: ./docker_config/backend/Dockerfile
    env_file:
      - ./docker_config/backend/backend.env
    restart: on-failure:3 
    command: /external_pentest/external_pentest/base/Rpc/rpc_server
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=external_pentest_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"