####################################################################
# domains will be used to:
#   - search for SMTP servers
#   - check for SPF, DKIM, DMARC
DOMAINS:
    - yandex.ru
    - ya.ru

# client emails will be used to:
#   - check user enumeration on every server
#   - send (to/from) emails
#   - send spoofed emails for antispam checks
CLIENT_EMAILS:
    - ShkolnikDanila228@yandex.ru

# attacker emails will be used to:
#   - send (to/from) emails
ATTACKER_EMAILS:
    - test@izoaz.ru

# you can add custom mail servers (domain name / ip) with or without port number
MAIL_SERVERS:
    - 87.250.250.89:25

####################################################################
# spoofing configurations
# your email address for getting client's feedback
SPOOF_RET_ADDR: "a.vasilenko@infosec.ru"
# person we are going to spoof on behalf of
SPOOFED_FROM: "A Vasilenko <a.vasilenko@infosec.ru>"


#####################################################################
# our basic configurations (usually not to be changed):
SPOOFED_BY: "test@spoofed.izoaz.ru"
DKIM_DOMAIN: "spoofed.izoaz.ru"
DKIM_SELECTOR: "gomaiz"
DKIM_KEY: "-----BEGIN RSA PRIVATE KEY-----\n\
MIICXAIBAAKBgQDKpC6zLL3Nzo5vQ+GMzukYSFwfjFgpFUjzroVyrTnvI/Oi/sBQ\n\
TAcFgH92+kkjIqtPNck+n8GdYjAsXzkwSsZgE9KpG/g2NVckGtssKm/4h9QIHbWD\n\
dX1l7tbOQMKCSojNH3MOBCqSeroDQC+1DTJ8cP7OoaYvz1M2Elg/YJPgnQIDAQAB\n\
AoGAUCXp9qIunDUjbuyZTDkWRq1wCmZXBEDP7tnLHFVZgbVlisVZySiY6lstjyBl\n\
RwlSWmz6oNNNH/OS/CnZk7kvhmGFODfXmSjuV0/Ty781TJtZu7aAArv8cZIrNCIz\n\
7rT8ewU1GWAMt6sOy3+SokqwmGNJopHBGNbmCbpb71HT+yECQQD9Cmbrp1mPGbrh\n\
lmV01vyKJIMoy3oBU7lCdftCLIXRgjDUY0zpzh2q63l08wb5FqiOg4xXLx0QTtAe\n\
hMfxqm7VAkEAzQLi0us3Z/SzSIvHt3k+gqeoRYQsACfXh6Qgk90JReerHtM1KomS\n\
ycIMnqojitxc2TUhNjZg5XJQUdm2ISTeqQJABRTEZE8D+V+m5QjEGMiIYa3CBHux\n\
g31O5wq/dOC3/zECEgG8daVx6xC3a6XFqhLOZ640jzue9cjfXP2FllC50QJAYywt\n\
O6jrgY9fFw3/S+ML+TpPbWl1u5GKcqRT2hOIA9gA8IVtZ6lrZ8xGPI7DaM4W4EAS\n\
U95UW0pEToQJ1di3GQJBALAQYkuJJKcRzPbdYDd4pPrGGv8h1dtrGfBvvDON/EKP\n\
Ud9WT+pb5YvVvI73B579ouHdxQnDGiRKleoJv2nlkhU=\n\
-----END RSA PRIVATE KEY-----"
#####################################################################
